<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Online Store</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <header>
        <h1>My Online Store</h1>
        <nav>
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#">Shop</a></li>
                <li><a href="#">About Us</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
        </nav>
    </header>
    <main>
        <section id="featured-products">
            <h2>Featured Products</h2>
            <!-- Display featured products here -->
            <div class="product">
                <img src="product1.jpg" alt="Product 1">
                <h3>Product 1</h3>
                <p>Description of product 1.</p>
                <button>Add to Cart</button>
            </div>
            <div class="product">
                <img src="product2.jpg" alt="Product 2">
                <h3>Product 2</h3>
                <p>Description of product 2.</p>
                <button>Add to Cart</button>
            </div>
            <!-- Add more products as needed -->
        </section>
        <section id="about-us">
            <h2>About Us</h2>
            <p>Welcome to My Online Store! We offer a wide range of products...</p>
        </section>
        <section id="contact">
            <h2>Contact Us</h2>
            <p>Feel free to contact us for any inquiries or assistance.</p>
        </section>
    </main>
    <footer>
        <p>&copy; 2024 My Online Store</p>
    </footer>
    <script src="script.js"></script>
</body>
</html>
/* Reset default styles */
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

/* Body styles */
body {
    font-family: Arial, sans-serif;
    line-height: 1.6;
}

/* Header styles */
header {
    background-color: #333;
    color: #fff;
    padding: 20px;
    text-align: center;
}

header h1 {
    margin-bottom: 10px;
}

header nav ul {
    list-style: none;
}

header nav ul li {
    display: inline;
    margin-right: 20px;
}

header nav ul li a {
    color: #fff;
    text-decoration: none;
}

/* Main styles */
main {
    padding: 20px;
}

/* Featured products styles */
#featured-products {
    margin-bottom: 40px;
}

.product {
    border: 1px solid #ccc;
    padding: 20px;
    margin-bottom: 20px;
}

.product img {
    max-width: 100%;
    height: auto;
    margin-bottom: 10px;
}

.product h3 {
    margin-bottom: 10px;
}

.product p {
    margin-bottom: 10px;
}

.product button {
    background-color: #333;
    color: #fff;
    border: none;
    padding: 5px 10px;
    cursor: pointer;
}

.product button:hover {
    background-color: #555;
}

/* Footer styles */
footer {
    background-color: #333;
    color: #fff;
    text-align: center;
    padding: 20px;
}
// JavaScript code for adding products to the cart
document.addEventListener('DOMContentLoaded', function() {
    const addToCartButtons = document.querySelectorAll('.product button');

    addToCartButtons.forEach(button => {
        button.addEventListener('click', function() {
            const product = this.closest('.product');
            const productName = product.querySelector('h3').innerText;
            alert(`Added ${productName} to the cart!`);
            // You can add more functionality here, such as updating the cart total or sending data to a server
        });
    });
});
